version: '3'
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./:/app
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      APP_NAME: 'Laravel'
      APP_ENV: 'development'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_DATABASE: 'laravel_development'
      DB_USERNAME: 'docker'
      DB_PASSWORD: 'docker'
      SESSION_DRIVER: 'redis'
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'redis'
      FILESYSTEM_DRIVER: 's3'
    volumes:
      - ./:/app
    expose:
      - 9000
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel_development'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
